// Package storage defines the Storage interface that all backends must implement.
//
// The interface covers the full job lifecycle: enqueue, dequeue, state transitions,
// scheduling, recurring jobs, continuations, server registry, distributed locks,
// counters, and cleanup.
package storage

import (
	"context"
	"time"

	domain "github.com/hrodrig/gfire/internal/job"
)

// Storage is the persistence backend for GFire.
// All methods must be safe for concurrent use.
type Storage interface {
	// ──────────────────────────────────────────────────────────────
	// Queues & Job Dispatch
	// ──────────────────────────────────────────────────────────────

	// Enqueue adds a job to the tail of the named queue.
	// Returns the job ID (generated by storage) and any error.
	Enqueue(ctx context.Context, queue string, job *domain.Job) (id string, err error)

	// Dequeue blocks until a job is available on any of the given queues,
	// or until the context is cancelled or timeout expires.
	// Returns a JobTicket with the job ID and a concurrency token.
	Dequeue(ctx context.Context, queues []string, timeout time.Duration) (*domain.JobTicket, error)

	// Requeue moves a job back to Enqueued state (orphan recovery, manual retry).
	Requeue(ctx context.Context, jobID string, reason string) error

	// ──────────────────────────────────────────────────────────────
	// State Machine
	// ──────────────────────────────────────────────────────────────

	// ApplyState transitions the job from expectedCurrent to newState.
	// Returns ErrStateConflict if the job is not in expectedCurrent.
	ApplyState(ctx context.Context, jobID string, expectedCurrent string, newState *domain.JobState) error

	// HeartbeatJob updates the job's last_progress timestamp.
	// Workers call this periodically for long-running jobs to prevent
	// orphan recovery from re-queueing them.
	// Returns ErrNotFound if the job doesn't exist.
	HeartbeatJob(ctx context.Context, jobID string) error

	// GetOrphanedJobs returns jobs in Processing state whose progress
	// heartbeat is older than the given stale duration.
	// Used by the Coordinator to detect jobs abandoned by dead workers.
	GetOrphanedJobs(ctx context.Context, staleAge time.Duration) ([]*domain.JobTicket, error)

	// GetJob retrieves a job with its full state history.
	GetJob(ctx context.Context, jobID string) (*domain.JobWithStates, error)

	// GetJobsByState retrieves jobs in a given state with pagination.
	GetJobsByState(ctx context.Context, state string, offset, limit int) ([]*domain.JobWithStates, error)

	// ──────────────────────────────────────────────────────────────
	// Queue Metadata
	// ──────────────────────────────────────────────────────────────

	// GetQueueLength returns the number of pending jobs in a queue.
	GetQueueLength(ctx context.Context, queue string) (int64, error)

	// GetQueues returns all known queue names.
	GetQueues(ctx context.Context) ([]string, error)

	// ──────────────────────────────────────────────────────────────
	// Server Registry
	// ──────────────────────────────────────────────────────────────

	// RegisterServer adds a server to the registry with a TTL.
	RegisterServer(ctx context.Context, server *domain.ServerInfo, ttl time.Duration) error

	// UnregisterServer removes a server from the registry.
	UnregisterServer(ctx context.Context, serverID string) error

	// Heartbeat refreshes a server's last heartbeat timestamp.
	Heartbeat(ctx context.Context, serverID string, ttl time.Duration) error

	// GetServers returns all registered servers.
	GetServers(ctx context.Context) ([]*domain.ServerInfo, error)

	// ──────────────────────────────────────────────────────────────
	// Scheduled Jobs (delayed / retry)
	// ──────────────────────────────────────────────────────────────

	// AddScheduled stores a job to be enqueued at the given time.
	AddScheduled(ctx context.Context, enqueueAt time.Time, job *domain.Job) (id string, err error)

	// GetDueScheduled returns all scheduled jobs whose enqueue_at <= now.
	GetDueScheduled(ctx context.Context, now time.Time, batchSize int) ([]*domain.JobTicket, error)

	// RemoveScheduled removes a job from the scheduled set.
	RemoveScheduled(ctx context.Context, jobID string) error

	// ──────────────────────────────────────────────────────────────
	// Recurring Jobs
	// ──────────────────────────────────────────────────────────────

	// UpsertRecurring creates or updates a recurring job definition.
	UpsertRecurring(ctx context.Context, entry *domain.RecurringJobEntry) error

	// RemoveRecurring deletes a recurring job definition.
	RemoveRecurring(ctx context.Context, id string) error

	// GetRecurringJobs returns all recurring job definitions.
	GetRecurringJobs(ctx context.Context) ([]*domain.RecurringJobEntry, error)

	// ──────────────────────────────────────────────────────────────
	// Continuations
	// ──────────────────────────────────────────────────────────────

	// AddContinuation registers a child job to run when the parent terminates.
	AddContinuation(ctx context.Context, parentID string, entry *domain.ContinuationEntry) error

	// GetContinuations returns all continuations for a parent domain.
	GetContinuations(ctx context.Context, parentID string) ([]*domain.ContinuationEntry, error)

	// RemoveContinuations deletes all continuations for a parent domain.
	RemoveContinuations(ctx context.Context, parentID string) error

	// ──────────────────────────────────────────────────────────────
	// Counters (dashboard stats)
	// ──────────────────────────────────────────────────────────────

	// IncrementCounter atomically adds delta to a named counter.
	IncrementCounter(ctx context.Context, key string, delta int64) error

	// GetCounter returns the current value of a named counter.
	GetCounter(ctx context.Context, key string) (int64, error)

	// GetAllCounters returns all counters with pagination.
	GetAllCounters(ctx context.Context, skip, limit int) (map[string]int64, error)

	// ──────────────────────────────────────────────────────────────
	// Distributed Lock
	// ──────────────────────────────────────────────────────────────

	// AcquireLock attempts to acquire a distributed lock for the given resource.
	// Returns the lock if successful, or ErrLockNotHeld if already held.
	AcquireLock(ctx context.Context, resource string, ttl time.Duration) (domain.Lock, error)

	// ──────────────────────────────────────────────────────────────
	// Maintenance
	// ──────────────────────────────────────────────────────────────

	// RemoveExpired deletes all jobs with terminal states older than cutoff.
	// Returns the number of deleted jobs.
	RemoveExpired(ctx context.Context, cutoff time.Time) (int64, error)

	// Close cleanly shuts down the storage backend, releasing connections.
	Close() error

	// ScheduleRetry moves a Failed job to Scheduled and sets enqueue_at (retry backoff).
	ScheduleRetry(ctx context.Context, jobID string, enqueueAt time.Time) error

	// SetJobResult stores handler stdout (JSON) on the job record before Succeeded.
	SetJobResult(ctx context.Context, jobID string, result []byte) error
}
